/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "BREVO_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DB_CLUSTERS_ARN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DB_NAME": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DB_SECRET_ARN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "JWT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}