/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ActivateDB": {
      "name": string
      "type": "sst.aws.Function"
    }
    "BREVO_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DB_CLUSTERS_ARN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DB_NAME": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DB_SECRET_ARN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HarvestersApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "HarvestersHubDatabase": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "reader": string
      "secretArn": string
      "type": "sst.aws.Aurora"
      "username": string
    }
    "HarvestersHubVpc": {
      "type": "sst.aws.Vpc"
    }
    "JWT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ReportGeneration": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}